### ISSUE TITLE
Trailing zeros

### ISSUE THREAD

**Issue by ullix** [flababah/cpuid.py#13]
Nice and fast! And all I need is name and vendor.
But: the Name is returned with 9 trailing zeros (shown below as '?'), which have to be removed. The Vendor comes back ok. 

`
03 12:44:42.183 DEBUG  : ....77 CPU Name      : Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz?????????

03 12:44:42.183 DEBUG  : ....78 CPU Vendor    : GenuineIntel
`
Linux Mint 21.2, Python 3.10.12

**Comment by flababah** [comment]
I assume you're using ```example.py```. It should be fixed in 7ae89df9d02034400417e9aa86ee58d4cd9bcb55. I never realized a null-terminated string was returned. Hope this helps. :)

**Comment by ullix** [comment]
That did help, thanks!

**Comment by ullix** [comment]
Sigh, I just realized: this is available only for X86, so not on any ARM, like Raspberry Pis. Too bad.

**Comment by flababah** [comment]
Yeah, this is specifically for the x86 CPUID instruction. I'm not sure if there is an equivalent ARM instruction. It probably wouldn't be too hard to create the machine code for ARM and use the same technique for injecting it (if one such instruction existed).

I don't think it makes sense adding support for ARM here, since this project is specifically about a x86 feature. The Python interface would also look quite different.
